# Generated by Django 4.2.4 on 2023-08-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Boss'), (3, 'Developer'), (4, 'Manager'), (5, 'Accountant')], verbose_name='Роль')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password_md5', models.CharField(blank=True, max_length=50, verbose_name='MD5 Пароля')),
            ],
        ),
    ]
